### ISSUE TITLE
server.py error

### ISSUE THREAD

**Issue by Harkyzera** [Igoorx/godfield-flash#5]
all requirements installed , python version 3.9.12

C:\Users\Pedro Henrique\Desktop\godfield-flash-master\server-src>server.py
Traceback (most recent call last):
  File "C:\Users\Pedro Henrique\Desktop\godfield-flash-master\server-src\server.py", line 6, in <module>
    from modules.user import User
  File "C:\Users\Pedro Henrique\Desktop\godfield-flash-master\server-src\modules\user.py", line 3, in <module>
    from types import NoneType
ImportError: cannot import name 'NoneType' from 'types' (C:\Users\Pedro Henrique\AppData\Local\Programs\Python\Python39\lib\types.py)

**Comment by Igoorx** [comment]
Sorry for the late reply and thanks for the issue! I don't even know why I was doing that lol
Fixed in https://github.com/Igoorx/godfield-flash/commit/dcb542f8472b7e0b16b7a9b5b791e04c749394ef
